# Generated by Django 4.1 on 2022-09-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quality',
            new_name='product_qty',
        ),
    ]
